# Generated by Django 5.2.6 on 2025-09-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_pet_is_available_alter_pet_category'),
    ]

    operations = [
    ]
